[pytest]
pythonpath = .
base_url = https://www.saucedemo.com
markers =
    negative: негативные тесты
    positive: позитивные тесты
    smoke: смоук тесты
    regression: регрессионные тесты
    auth: тесты на функционал авторизации

